version: 2

jobs:
  build:
    docker:
      - image: circleci/ruby:2.4.4-node
        environment:
          RAILS_ENV: test

    steps:
      - checkout
      - run:
          name: Bundle Install
          command: bundle check || bundle install
      - run:
          name: Run rspec in parallel
          command: bundle exec rspec --profile 10 --format RspecJunitFormatter --out test_results/rspec.xml --format progress $(circleci tests glob "spec/**/*_spec.rb" | circleci tests split --split-by=timings)
      - store_test_results:
          path: test_results

workflows:
  version: 2
  inciweb_test:
    jobs:
      - build
